---

policy:
  - tags: ['alpha', 'beta']
    feedback:
      frozen-state: |
        🥶 We are currently in ...
        🙏 Please ...
      unfreeze-state: |
        😎 We are no longer in ...

  - tags: ['^\S*-rc\d$']
    feedback:
      frozen-state: |
        We are currently in a development freeze phase.
        Please ...
      unfreeze-state: |
        We had successfully released a new major release.
        We are no longer in a development freeze phase.

  - tags: ['^v\d\.\d\.\d$']
    feedback:
      frozen-state: |
        Hi from "frozen state" ...
      unfreeze-state: |
        Hi from "unfreeze state" ...

...
