---

name: Development Freezer
description: Notify contributors about ongoing development freeze.

branding:
  icon: archive
  color: blue

inputs:
  token:
    required: true
    description: GitHub token used to set issue labels

runs:
  using: 'node16'
  main: 'dist/index.js'
